{{ if eq .Values.createPvc true }}
{{ if eq .Values.platform "kind" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.claimName }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{ else if eq .Values.platform "ibm" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.claimName }}
  annotations:
    ibm.io/auto-create-bucket: "false"
    ibm.io/auto-delete-bucket: "false"
    ibm.io/bucket: {{ .Values.cos.bucket | quote }}
    ibm.io/quota-limit: "false"
    ibm.io/endpoint: {{ .Values.cos.endpoint | quote }}
    ibm.io/tls-cipher-suite: "default"
    ibm.io/secret-name: {{ .Values.cos.secretName | quote }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.cos.storageSize | quote }}
  storageClassName: {{ .Values.storageClassName | quote }}
{{ else }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gateway-volume
  labels:
    type: local
  annotations:
    pv.beta.kubernetes.io/gid: "100"
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/tmp"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.claimName }}
spec:
  storageClassName:  {{ .Values.storageClassName | quote }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{ end }}
{{ end }}