apiVersion: v2
name: quantum-serverless
description: Quantum-Serverless helm chart that contains different dependencies.

type: application

version: 0.1.2
appVersion: "0.1.2"

dependencies:
  - name: gateway
    condition: gatewayEnable
    version: 0.1.2
  - name: jupyter
    condition: jupyterEnable
    version: 0.1.2
  - name: nginx-ingress-controller
    condition: nginxIngressControllerEnable
    version: 9.7.2
    repository: https://charts.bitnami.com/bitnami
  - name: kuberay-operator
    condition: kuberayOperatorEnable
    version: 0.5.1
    repository: https://ray-project.github.io/kuberay-helm
  - name: redis
    condition: redisEnable
    version: 17.11.3
    repository: https://charts.bitnami.com/bitnami
  - name: keycloak
    condition: keycloakEnable
    version: 13.4.1
    repository: https://charts.bitnami.com/bitnami
  - name: repository
    condition: repositoryEnable
    version: 0.1.2
  - name: kube-prometheus-stack
    condition: prometheusEnable
    version: 45.31.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki
    condition: lokiEnable
    version: 4.10.0
    repository: https://grafana.github.io/helm-charts
  - name: promtail
    condition: promtailEnable
    version: 6.11.2
    repository: https://grafana.github.io/helm-charts
