name: Docker notebook tests

on:
  pull_request:
    branches: [ main ]
    
jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - ray-python: 'py39'
            notebook-python: '3.9'
            gateway-python: '3.9.16'
          - ray-python: 'py311'
            notebook-python: '3.11'
            gateway-python: '3.11.4'
    steps:
      - uses: actions/checkout@v3
      - name: Build the containers
        run: RAYPYTHON=${{ matrix.ray-python }} NOTEBOOKPYTHON=${{ matrix.notebook-python }} GATEWAYPYTHON=${{ matrix.gateway-python }} docker compose -f docker-compose-dev.yml --profile jupyter build
      - name: Run the jupyter profile
        run: RAYPYTHON=${{ matrix.ray-python }} NOTEBOOKPYTHON=${{ matrix.notebook-python }} GATEWAYPYTHON=${{ matrix.gateway-python }} docker compose -f docker-compose-dev.yml --profile jupyter up -d
      - name: Give containers time to initialize
        shell: bash
        run: sleep 90
      - name: Test notebooks in the docker environment
        shell: bash
        run: docker exec qs-jupyter "bash" "-c" "pip install nbmake pytest && pytest --nbmake --ignore=/home/jovyan/serverless/guides/07_working_with_datasets.ipynb /home/jovyan/serverless/"
      - name: Dump logs on failure
        if: ${{ failure() }}
        run: |
          docker compose logs gateway
          docker compose logs jupyter
