name: Notebook LocalClient tests

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: patch notebooks
        shell: bash
        run: |
          for f in tests/basic/*.py; do sed -i "s/import ServerlessClient/import LocalClient/;s/= ServerlessClient(/= LocalClient(/;/token=os\.environ\.get/d;/host=os\.environ\.get/d" "$f"; done
          for f in tests/experimental/*.py; do sed -i "s/import ServerlessClient/import LocalClient/;s/= ServerlessClient(/= LocalClient(/;/token=os\.environ\.get/d;/host=os\.environ\.get/d" "$f"; done
          rm tests/basic/06_function.py
      - name: install dependencies
        shell: bash
        run: pip install client/
      - name: Run basic notebooks
        shell: bash
        run: |
          cd tests/basic
          for f in *.py; do echo "$f" && IN_TEST=True python "$f"; done
          cd -
      - name: Run experimental notebooks
        shell: bash
        run: |
          cd tests/experimental
          for f in *.py; do echo "$f" && IN_TEST=True python "$f"; done
          cd -
