name: Notebook LocalProvider tests

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: patch notebooks
        shell: bash
        run: |
          for f in tests/basic/*.py; do sed -i "s/import ServerlessProvider/import LocalProvider/;s/= ServerlessProvider(/= LocalProvider(/;/token=os\.environ\.get/d;/host=os\.environ\.get/d" "$f"; done
          for f in tests/experimental/*.py; do sed -i "s/import ServerlessProvider/import LocalProvider/;s/= ServerlessProvider(/= LocalProvider(/;/token=os\.environ\.get/d;/host=os\.environ\.get/d" "$f"; done
      - name: install dependencies
        shell: bash
        run: pip install client/
      - name: Run basic notebooks
        shell: bash
        run: |
          cd tests/basic
          for f in *.py; do IN_TEST=True python "$f"; done
          cd -
      - name: Run experimental notebooks
        shell: bash
        run: |
          cd tests/experimental
          for f in *.py; do IN_TEST=True python "$f"; done
          cd -
